# Generated by Django 2.2.6 on 2019-10-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_ingredient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
